builds:
  - id: otfd
    ldflags:
      - -s -w
      - -X github.com/jpetrucciani/otf/internal.Version={{.Version}}
      - -X github.com/jpetrucciani/otf/internal.Commit={{.Commit}}
      - -X github.com/jpetrucciani/otf/internal.Built={{.Date}}
    main: ./cmd/otfd
    binary: otfd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm64
  - id: otf-agent
    ldflags:
      - -s -w
      - -X github.com/jpetrucciani/otf/internal.Version={{.Version}}
      - -X github.com/jpetrucciani/otf/internal.Commit={{.Commit}}
      - -X github.com/jpetrucciani/otf/internal.Built={{.Date}}
    main: ./cmd/otf-agent
    binary: otf-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm64
  - id: otf
    ldflags:
      - -s -w
      - -X github.com/jpetrucciani/otf/internal.Version={{.Version}}
      - -X github.com/jpetrucciani/otf/internal.Commit={{.Commit}}
      - -X github.com/jpetrucciani/otf/internal.Built={{.Date}}
    main: ./cmd/otf
    binary: otf
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm64
archives:
  - id: otfd
    builds:
      - otfd
    format: zip
    name_template: 'otfd_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  - id: otf-agent
    builds:
      - otf-agent
    format: zip
    name_template: 'otf-agent_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  - id: otf
    builds:
      - otf
    format: zip
    name_template: 'otf_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - otfd
    image_templates:
      - 'jpetrucciani/otfd:latest-amd64'
      - 'jpetrucciani/otfd:{{ .Version }}-amd64'
    skip_push: auto
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - '--pull'
      - '--platform=linux/amd64'
  - goos: linux
    goarch: arm64
    ids:
      - otfd
    image_templates:
      - 'jpetrucciani/otfd:latest-arm64'
      - 'jpetrucciani/otfd:{{ .Version }}-arm64'
    skip_push: auto
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - '--pull'
      - '--platform=linux/arm64'
  - goos: linux
    goarch: amd64
    ids:
      - otf-agent
    image_templates:
      - 'jpetrucciani/otf-agent:latest-amd64'
      - 'jpetrucciani/otf-agent:{{ .Version }}-amd64'
    skip_push: auto
    dockerfile: Dockerfile.agent
    use: buildx
    build_flag_templates:
      - '--pull'
      - '--platform=linux/amd64'
  - goos: linux
    goarch: arm64
    ids:
      - otf-agent
    image_templates:
      - 'jpetrucciani/otf-agent:latest-arm64'
      - 'jpetrucciani/otf-agent:{{ .Version }}-arm64'
    skip_push: auto
    dockerfile: Dockerfile.agent
    use: buildx
    build_flag_templates:
      - '--pull'
      - '--platform=linux/arm64'
docker_manifests:
  - name_template: 'jpetrucciani/otfd:latest'
    image_templates:
      - 'jpetrucciani/otfd:latest-amd64'
      - 'jpetrucciani/otfd:latest-arm64'
  - name_template: 'jpetrucciani/otfd:{{ .Version }}'
    image_templates:
      - 'jpetrucciani/otfd:{{ .Version }}-amd64'
      - 'jpetrucciani/otfd:{{ .Version }}-arm64'
  - name_template: 'jpetrucciani/otf-agent:latest'
    image_templates:
      - 'jpetrucciani/otf-agent:latest-amd64'
      - 'jpetrucciani/otf-agent:latest-arm64'
  - name_template: 'jpetrucciani/otf-agent:{{ .Version }}'
    image_templates:
      - 'jpetrucciani/otf-agent:{{ .Version }}-amd64'
      - 'jpetrucciani/otf-agent:{{ .Version }}-arm64'
release:
  footer: |
    ## Docker images

    * `jpetrucciani/otfd:{{ .Version }}`
    * `jpetrucciani/otf-agent:{{ .Version }}`
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  skip: true
