FROM alpine:3.20

# bubblewrap is for sandboxing, and git permits pulling modules via
# the git protocol
RUN apk add --no-cache bubblewrap git python3 py3-pip aws-cli

COPY otf-agent /usr/local/bin/otf-agent

ENTRYPOINT ["/usr/local/bin/otf-agent"]
